### ISSUE TITLE
wingpanel-interface plugin causing gala crashes on focal daily iso

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/wingpanel#278]
Here's the backtrace:
```
#0  0x00007f8b0dbc1669 in g_type_check_instance_is_fundamentally_a () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007f8b0db9e942 in g_object_ref () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007f8b04017423 in _g_object_ref0 (self=0x225b8530) at ../wingpanel-interface/BackgroundManager.vala:96
#3  0x00007f8b04017581 in wingpanel_interface_background_manager_update_current_workspace (self=0x55c4228b1b50)
    at ../wingpanel-interface/BackgroundManager.vala:96
#4  0x00007f8b0401705a in __lambda13_ (self=0x55c4228b1b50, obj=0x55c4228b1b50, res=0x55c4227fa100)
    at ../wingpanel-interface/BackgroundManager.vala:56
#5  0x00007f8b0401708b in ___lambda13__gasync_ready_callback
    (source_object=0x55c4228b1b50, res=0x55c4227fa100, self=0x55c4228b1b50) at ../wingpanel-interface/BackgroundManager.vala:54
#6  0x00007f8b0dc98bf9 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007f8b0dc997ed in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007f8b04018386 in wingpanel_interface_background_manager_update_bk_color_info_co (_data_=0x55c4229a3390)
    at ../wingpanel-interface/BackgroundManager.vala:150
#9  0x00007f8b04017ded in _wingpanel_interface_background_manager_update_bk_color_info_co_gsource_func (self=0x55c4229a3390)
    at BackgroundManager.c:796
#10 0x00007f8b0401807a in __lambda11_ (_data1_=0x55c4228b3aa0, obj=0x0, res=0x55c4227fa040)
    at ../wingpanel-interface/BackgroundManager.vala:162
#11 0x00007f8b04018137 in ___lambda11__gasync_ready_callback (source_object=0x0, res=0x55c4227fa040, self=0x55c4228b3aa0)
    at ../wingpanel-interface/BackgroundManager.vala:156
#12 0x00007f8b0dc98bf9 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#13 0x00007f8b0dc997ed in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#14 0x00007f8b0401ca7f in wingpanel_interface_utils_get_background_color_information_co (_data_=0x55c4229a4190)
    at ../wingpanel-interface/Utils.vala:219
#15 0x00007f8b0401bfaf in __lambda10_ (_data3_=0x55c4229690a0) at ../wingpanel-interface/Utils.vala:212
#16 0x00007f8b0401c02a in ___lambda10__wingpanel_interface_utils_dummy_offscreen_effect_done_painting
    (_sender=0x55c422567110, self=0x55c4229690a0) at ../wingpanel-interface/Utils.vala:93
#17 0x00007f8b0db99802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007f8b0dbad814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007f8b0dbb8b9e in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007f8b0dbb90d3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007f8b0401a96c in __lambda9_ (self=0x55c422567110) at ../wingpanel-interface/Utils.vala:35
#22 0x00007f8b0401a994 in ___lambda9__gsource_func (self=0x55c422567110) at Utils.c:201
#23 0x00007f8b0daaddae in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--c
#24 0x00007f8b0daae160 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007f8b0daae453 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007f8b0ce67390 in meta_run () at /lib/x86_64-linux-gnu/libmutter-5.so.0
#27 0x000055c42170b998 in  ()
#28 0x0000000121743cd0 in  ()
#29 0x00007ffd268f4218 in  ()
#30 0x0000000000000000 in  ()
```

**Comment by davidmhewitt** [comment]
This will apparently be fixed when wingpanel next rebuilds on launchpad. There's been an api change in gala.

**Comment by davidmhewitt** [comment]
This has not been resolved by a rebuild of wingpanel, the backtrace remains the same.

**Comment by davidmhewitt** [comment]
Resolved in latest build.
